# Fly.io deployment configuration for Word Bocce

app = "word-bocce"
primary_region = "sjc"

[build]
  [build.args]

[env]
  MODEL_PATH = "./embeddings/glove-100.bin"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/api"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
